### ISSUE TITLE
Please use a different name

### ISSUE THREAD

**Issue by kirb** [iMokhles/TheosUI#1]
"TheosUI" implies that this could be an official Theos project, which it isn't. It makes the distinction between official and 3rd-party projects hard, and we'll end up getting bug reports for your project, and vice versa. Considering recent events in the jailbreak community, I figured this would be common sense by now… It's also quite unoriginal, you could be a lot more creative! "[something] for Theos" is acceptable.

**Comment by iMokhles** [comment]
- name will be changed ASAP 
  :+1:
