### ISSUE TITLE
Why is this project made in XCode?

### ISSUE THREAD

**Issue by MiseroMCS** [iMokhles/TheosUI#2]
Should it not be a theos/monolith project? This project likely would need root access.

**Comment by iMokhles** [comment]
i'm testing it on real jailbroken device not simulator ( it works fine to create projects ( in sandbox ) ) also it still beta ( so i'm testing everything to be sure it works fine before opening it for root )

**Comment by Razzile** [comment]
@MiseroMCS apps made in xcode can still run as root, made a few myself
